import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next";
import Providers from "./providers";
import { Suspense } from "react";
import { Spinner } from "@/components/shared/Spinner";
import { Toaster } from 'sonner';

const sarabun = Sarabun({
  variable: "--font-sarabun",
  subsets: ["latin", "thai"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sarabun.variable} antialiased`}
      >
        <Providers>
          <Suspense
            fallback={
              <div className="w-full bg-white min-h-screen transition duration-500 ease-in-out overflow-y-auto overflow-x-hidden flex items-center justify-center">
                <Spinner />
              </div>
            }
          >
            <NuqsAdapter>{children}</NuqsAdapter>
          </Suspense>
          <Toaster/>
        </Providers>
      </body>
    </html>
  );
}